/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacasulono;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Trentim
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        btnLimpar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("CadastroFuncionario6"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Funcionário:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 68, -1, 30));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 69, 79, -1));

        jLabel2.setText("Nome do Funcionário:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 122, -1, -1));

        jLabel3.setText("Login:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 168, -1, -1));
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 162, 146, -1));

        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 168, -1, -1));
        getContentPane().add(pfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 162, 130, -1));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 223, -1, 40));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 223, -1, 40));

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 223, -1, 40));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 116, 200, -1));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 223, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiniLogo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 6, -1, -1));

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lupa_1.png"))); // NOI18N
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 66, 36, 32));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        new Menu().show();
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try {
            /*Connection - classe usada para estabelecer uma conexão com o banco. Neste momento devemos informar
             o endereço do servidor(IP) o nome do Banco e o usuário e nenha de acesso   */
            Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;// String para receber a Scrip(O comando SQL que será usado-Insert/Update/DLETE)
            sql = "INSERT INTO telalogin(Nome_do_Funcionario,Login,Senha)VALUES(?,?,?)";
            /*uma forma de você fazer uma inserção no banco mais segura,
             onde você prepara os parametros para serem inseridos */
            PreparedStatement ps;
            ps = (PreparedStatement) con.prepareStatement(sql);

            ps.setString(1, txtNome.getText());
            ps.setString(2, txtLogin.getText());
            ps.setString(3, pfSenha.getText());

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Falha no Cadastro");
            }
        } catch (SQLException ex)//Se ocorrer algum erro uma mensagem é exibida.
        {
            JOptionPane.showMessageDialog(null, "SQLException: ");
            JOptionPane.showMessageDialog(null, "SQLException: " + ex.getMessage() + "\nSQLState: " + ex.getSQLState()
                    + "\nVendorError: " + ex.getErrorCode());
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {

            Connection con;//Objeto para criar uma ligação com o banco de dados
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;// String para receber a Scrip(O comando SQL que será usado-Insert/Update/DLETE)
            sql = "UPDATE telalogin set Nome_do_Funcionario=?,Login=?,Senha=? where ID_Funcionario=?";//Script para alterar dados no BD
            /*uma forma de você fazer uma inserção no banco mais segura,
             onde você prepara os parametros para serem inseridos */
            PreparedStatement ps;
            ps = (PreparedStatement) con.prepareStatement(sql);
            ps.setString(1, txtNome.getText());
            ps.setString(2, txtLogin.getText());
            ps.setString(3, pfSenha.getText());
            ps.setString(4, txtID.getText());

            int res = ps.executeUpdate();//executa o comando e retorna a qtd de registros incluidos
            if (res > 0) {//se for inserido um registro res>0!, deu certo.
                JOptionPane.showMessageDialog(null, "Alterado com sucesso");
            } else {//se nao deu certo
                JOptionPane.showMessageDialog(null, "Nenhum registro alterado");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQLException: " + ex.getMessage() + "\nSQLState: " + ex.getSQLState() + "\nVendedorError: " + ex.getErrorCode());
        }

    }

    private void limpar() {
        txtID.setText(" ");
        txtLogin.setText(" ");
        txtNome.setText(" ");
        pfSenha.setText("");
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql = null;
            sql = "SELECT * FROM telalogin WHERE ID_Funcionario LIKE ?";
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, "%" + txtID.getText() + "%");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                txtLogin.setText(rs.getString("Login"));
                txtNome.setText(rs.getString("Nome_do_Funcionario"));
                pfSenha.setText(rs.getString("Senha"));
            } else {
                JOptionPane.showMessageDialog(null, "Registro não encontrado", "Mensagem", JOptionPane.WARNING_MESSAGE);
            }
       
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQLException" + ex.getMessage() + "\nSQLState" + ex.getSQLState() + "\nVendorError");

        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

}
