/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacasulono;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Trentim
 */
public class ComposicaoFamiliar extends javax.swing.JFrame {

    /**
     * Creates new form ComposicaoFamiliar
     */
    public ComposicaoFamiliar() {
        getContentPane().setBackground(Color.white);
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblLogo = new javax.swing.JLabel();
        lblComposicao = new javax.swing.JLabel();
        chSituacaoFamiliar = new javax.swing.JCheckBox();
        chOrfao = new javax.swing.JCheckBox();
        chReintegracao = new javax.swing.JCheckBox();
        chFamiliaExtensa = new javax.swing.JCheckBox();
        chPoderFamiliar = new javax.swing.JCheckBox();
        chGuardaTutela = new javax.swing.JCheckBox();
        chSemInformacao = new javax.swing.JCheckBox();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblParentesco = new javax.swing.JLabel();
        cbParentesco = new javax.swing.JComboBox<>();
        lblIdade = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        lblEscolaridade = new javax.swing.JLabel();
        cbEscolaridade = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbOcupacao = new javax.swing.JComboBox<>();
        lblRenda = new javax.swing.JLabel();
        ftxtRenda = new javax.swing.JFormattedTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        cbSexo = new javax.swing.JComboBox<>();
        btnGravar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblTelefone = new javax.swing.JLabel();
        btnProx = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        txtTelefone = new javax.swing.JFormattedTextField();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Composição Familiar");
        setName("ComposicaoFamiliar"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiniLogo.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(0, 0, 300, 147);

        lblComposicao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblComposicao.setText("COMPOSIÇÃO FAMÍLIAR");
        getContentPane().add(lblComposicao);
        lblComposicao.setBounds(460, 120, 300, 32);

        chSituacaoFamiliar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSituacaoFamiliar.setText("Em estudo e acompanhamento da situação familiar");
        getContentPane().add(chSituacaoFamiliar);
        chSituacaoFamiliar.setBounds(70, 180, 350, 18);

        chOrfao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chOrfao.setText("Criança/Adolescente Órfão");
        getContentPane().add(chOrfao);
        chOrfao.setBounds(620, 180, 200, 18);

        chReintegracao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chReintegracao.setText("Preparação para reintegração familiar (Família natural)");
        getContentPane().add(chReintegracao);
        chReintegracao.setBounds(70, 220, 370, 18);

        chFamiliaExtensa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chFamiliaExtensa.setText("Preparação para reintegração familiar (Família extensa)");
        getContentPane().add(chFamiliaExtensa);
        chFamiliaExtensa.setBounds(620, 220, 380, 18);

        chPoderFamiliar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chPoderFamiliar.setText("Poder familiar destituído");
        getContentPane().add(chPoderFamiliar);
        chPoderFamiliar.setBounds(70, 260, 180, 18);

        chGuardaTutela.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chGuardaTutela.setText("Em processo de guarda/tutela/adoção");
        getContentPane().add(chGuardaTutela);
        chGuardaTutela.setBounds(620, 260, 280, 18);

        chSemInformacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSemInformacao.setText("Sem informação da família");
        getContentPane().add(chSemInformacao);
        chSemInformacao.setBounds(70, 300, 200, 18);

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setText("Nome completo:");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 385, 101, 17);
        getContentPane().add(txtNome);
        txtNome.setBounds(140, 380, 308, 28);

        lblParentesco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblParentesco.setText("Parentesco:");
        getContentPane().add(lblParentesco);
        lblParentesco.setBounds(460, 385, 90, 17);

        cbParentesco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1. Própria criança/adolescente acolhido ", "2.Mãe", "3.Pai  ", "4.Madrasta  ", "5.Padrasto  ", "6.Irmã(o) ", "7.Avó(ô)  ", "8.Tia(o) ", "9.Prima(o)   ", "10.Outros " }));
        getContentPane().add(cbParentesco);
        cbParentesco.setBounds(540, 380, 284, 27);

        lblIdade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdade.setText("Idade (Ano(s)/Mês(es):");
        getContentPane().add(lblIdade);
        lblIdade.setBounds(840, 385, 139, 17);
        getContentPane().add(txtIdade);
        txtIdade.setBounds(980, 380, 122, 28);

        lblSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSexo.setText("Sexo:");
        getContentPane().add(lblSexo);
        lblSexo.setBounds(30, 435, 35, 17);

        lblEscolaridade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEscolaridade.setText("Escolaridade:");
        getContentPane().add(lblEscolaridade);
        lblEscolaridade.setBounds(200, 435, 86, 17);

        cbEscolaridade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "0.Sem idade escolar", "1.Creche", "2.Pré-escola", "3.Ensino Fundamental", "4.Ensino Médio", "5.Ensino Fundamental EJA", "5.Ensino Médio EJA", "7.Alfabetização para Adultos", "8.Superior/Aperfeiçoamento/Especialização/Doutorado", "9.Pré-Vestibular", "10.Nunca frequentou a escola, mas sabe ler e escrever", "11.Nunca frequentou a escola e não sabe ler ou escrever" }));
        getContentPane().add(cbEscolaridade);
        cbEscolaridade.setBounds(290, 430, 394, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Ocupação:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(710, 435, 69, 17);

        cbOcupacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbOcupacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1. Não trabalha", "2.Trabalhador por conta própria (autônomo/bico)", "3.Temporário em área rural", "4.Empregado sem carteira assinada", "5.Empregado com carteira assinada", "6.Trabalhador doméstico sem carteira assinada", "7. Trabalhador doméstico com carteira assinada", "8. Trabalhador não remunerado", "9. Militar ou servidor público", "10.Empregador", "11.Estagiário", "12.Aprendiz  " }));
        getContentPane().add(cbOcupacao);
        cbOcupacao.setBounds(780, 430, 297, 30);

        lblRenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRenda.setText("Renda(R$):");
        getContentPane().add(lblRenda);
        lblRenda.setBounds(30, 485, 74, 17);

        ftxtRenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        getContentPane().add(ftxtRenda);
        ftxtRenda.setBounds(110, 480, 129, 28);

        lblEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço:");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(250, 485, 65, 17);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(320, 480, 354, 28);

        cbSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "M - Masculino", "F - Feminino" }));
        getContentPane().add(cbSexo);
        cbSexo.setBounds(70, 430, 117, 30);

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(660, 530, 89, 40);

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(760, 530, 90, 40);

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone:");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(690, 485, 56, 17);

        btnProx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Seta.png"))); // NOI18N
        btnProx.setText("Próxima etapa");
        btnProx.setBorderPainted(false);
        btnProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxActionPerformed(evt);
            }
        });
        getContentPane().add(btnProx);
        btnProx.setBounds(960, 530, 130, 40);

        btnAnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SetaE.png"))); // NOI18N
        btnAnt.setText("Etapa Anterior");
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnt);
        btnAnt.setBounds(520, 530, 130, 40);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(860, 530, 90, 40);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(750, 480, 110, 28);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fundo.jpg"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1110, 600);

        setSize(new java.awt.Dimension(1110, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        cbEscolaridade.setSelectedItem("Selecione");
        cbOcupacao.setSelectedItem("Selecione");
        cbParentesco.setSelectedItem("Selecione");
        cbSexo.setSelectedItem("Selecione");
        chFamiliaExtensa.setSelected(false);
        chGuardaTutela.setSelected(false);
        chReintegracao.setSelected(false);
        chSemInformacao.setSelected(false);
        chSituacaoFamiliar.setSelected(false);
        ftxtRenda.setText("");
        txtEndereco.setText("");
        txtIdade.setText("");
        txtNome.setText("");
        chPoderFamiliar.setSelected(false);
        chOrfao.setSelected(false);
        txtTelefone.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try {
            /*Connection - classe usada para estabelecer uma conexão com o banco. Neste momento devemos informar
            o endereço do servidor(IP) o nome do Banco e o usuário e nenha de acesso   */
            Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;// String para receber a Scrip(O comando SQL que será usado-Insert/Update/DLETE)
            sql = "INSERT INTO composicao_familiar(Em_est_e_acomp_da_sit_fami,Prep_p_reint_fam_nat,Pod_fam_dest,S_inf_d_fam,Cri_Adol_orf,"
                    + "Prep_p_reint_fam_ext,Em_proc_d_gua_tut_ad,Nome_Completo,Idade,Escolaridade,Parentesco,Ocupacao,"
                    + "Sexo,Renda,Endereco,Telefone)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            /*uma forma de você fazer uma inserção no banco mais segura,
            onde você prepara os parametros para serem inseridos */
            PreparedStatement ps;
            ps = (PreparedStatement) con.prepareStatement(sql);
            if (chSituacaoFamiliar.isSelected()) {
                ps.setBoolean(1, true);
            } else {
                ps.setBoolean(1, false);
            }
            if (chReintegracao.isSelected()) {
                ps.setBoolean(2, true);
            } else {
                ps.setBoolean(2, false);
            }
            if (chPoderFamiliar.isSelected()) {
                ps.setBoolean(3, true);
            } else {
                ps.setBoolean(3, false);
            }
            if (chSemInformacao.isSelected()) {
                ps.setBoolean(4, true);
            } else {
                ps.setBoolean(4, false);
            }
            if (chOrfao.isSelected()) {
                ps.setBoolean(5, true);
            } else {
                ps.setBoolean(5, false);
            }
            if (chFamiliaExtensa.isSelected()) {
                ps.setBoolean(6, true);
            } else {
                ps.setBoolean(6, false);
            }
            if (chGuardaTutela.isSelected()) {
                ps.setBoolean(7, true);
            } else {
                ps.setBoolean(7, false);
            }
            ps.setString(8, txtNome.getText());
            ps.setString(9, txtIdade.getText());
            ps.setString(10, cbEscolaridade.getSelectedItem().toString());
            ps.setString(11, cbParentesco.getSelectedItem().toString());
            ps.setString(12, cbOcupacao.getSelectedItem().toString());
            ps.setString(13, cbSexo.getSelectedItem().toString());
            ps.setString(14, ftxtRenda.getText());
            ps.setString(15, txtEndereco.getText());
            ps.setString(16, txtTelefone.getText());

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Falha no Cadastro");
            }
        } catch (SQLException ex)//Se ocorrer algum erro uma mensagem é exibida.
        {
            JOptionPane.showMessageDialog(null, "SQLException: ");
            JOptionPane.showMessageDialog(null, "SQLException: " + ex.getMessage() + "\nSQLState: " + ex.getSQLState()
                    + "\nVendorError: " + ex.getErrorCode());
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxActionPerformed
        InformacoesAdicionaisFamilia pnelso = new InformacoesAdicionaisFamilia();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnProxActionPerformed

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        JF_3CDA pnelso = new JF_3CDA();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnAntActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu pnelso = new Menu();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComposicaoFamiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComposicaoFamiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComposicaoFamiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComposicaoFamiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComposicaoFamiliar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnProx;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbEscolaridade;
    private javax.swing.JComboBox<String> cbOcupacao;
    private javax.swing.JComboBox<String> cbParentesco;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JCheckBox chFamiliaExtensa;
    private javax.swing.JCheckBox chGuardaTutela;
    private javax.swing.JCheckBox chOrfao;
    private javax.swing.JCheckBox chPoderFamiliar;
    private javax.swing.JCheckBox chReintegracao;
    private javax.swing.JCheckBox chSemInformacao;
    private javax.swing.JCheckBox chSituacaoFamiliar;
    private javax.swing.JFormattedTextField ftxtRenda;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblComposicao;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEscolaridade;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblParentesco;
    private javax.swing.JLabel lblRenda;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
