/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacasulono;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author VPLima-Inf181
 */
public class InfCA extends javax.swing.JFrame {

    /**
     * Creates new form InfCA
     */
    public InfCA() {
        initComponents();
        getContentPane().setBackground(Color.white);
        panel1.setBackground(Color.white);
        chbSemRegistro.setBackground(new Color(0, 0, 0, 0));
        chbIdadePresu.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        checkbox4 = new java.awt.Checkbox();
        lblTransfServ = new javax.swing.JLabel();
        txtTransfDeServ = new javax.swing.JTextField();
        lblNomeComp = new javax.swing.JLabel();
        lblComoSerCha = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox();
        lblCorRaca = new javax.swing.JLabel();
        cbxCorRaca = new javax.swing.JComboBox();
        lblDataNasc = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblNacionalidade = new javax.swing.JLabel();
        lblNaturalidade = new javax.swing.JLabel();
        txtNaturalidade = new javax.swing.JTextField();
        lblEndUltCasa = new javax.swing.JLabel();
        txtEndUltCasa = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txtNomeComp = new javax.swing.JTextField();
        ftfDataNasc = new javax.swing.JFormattedTextField();
        ftfCep = new javax.swing.JFormattedTextField();
        ftfIdade = new javax.swing.JFormattedTextField();
        btnPaginaAnt = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnProxiPag = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        cbxNacionalidade = new javax.swing.JComboBox();
        btnMenu = new javax.swing.JButton();
        chbSemRegistro = new javax.swing.JCheckBox();
        chbIdadePresu = new javax.swing.JCheckBox();
        txtComoSerCha = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(160, 80));
        setName(""); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(1250, 750));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiniLogo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 330, 140);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setText("Informações sobre a Criança/Adolescente");
        lblTitulo.setName(""); // NOI18N
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(440, 130, 620, 32);

        panel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        checkbox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkbox1.setLabel("Encaminhada(o)/ Vinda(o) de outro Município ou Estado");

        checkbox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkbox2.setLabel("Uso de álcool/drogas");

        checkbox3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkbox3.setLabel("Deficiência ou problema de saúde grave");

        checkbox4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkbox4.setLabel("Acolhida(o) anteriormente");

        lblTransfServ.setBackground(new java.awt.Color(255, 255, 255));
        lblTransfServ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTransfServ.setText("Transferida(o) de outro serviço de acolhimento? Qual?");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTransfServ)
                    .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransfDeServ, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTransfServ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTransfDeServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(panel1);
        panel1.setBounds(0, 470, 440, 220);

        lblNomeComp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNomeComp.setText("Nome Completo:");
        getContentPane().add(lblNomeComp);
        lblNomeComp.setBounds(10, 215, 110, 17);

        lblComoSerCha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblComoSerCha.setText("Como prefere ser chamado(a):");
        getContentPane().add(lblComoSerCha);
        lblComoSerCha.setBounds(10, 255, 200, 20);

        lblSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSexo.setText("Sexo:");
        getContentPane().add(lblSexo);
        lblSexo.setBounds(10, 338, 35, 17);

        cbxSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Masculino", "Feminino" }));
        cbxSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(cbxSexo);
        cbxSexo.setBounds(50, 330, 120, 30);

        lblCorRaca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCorRaca.setText("Cor/Raça:");
        getContentPane().add(lblCorRaca);
        lblCorRaca.setBounds(200, 340, 64, 17);

        cbxCorRaca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxCorRaca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Branca", "Preta", "Parda", "Amarela", "Indígena" }));
        getContentPane().add(cbxCorRaca);
        cbxCorRaca.setBounds(270, 335, 120, 27);

        lblDataNasc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDataNasc.setText("Data de nascimento:");
        getContentPane().add(lblDataNasc);
        lblDataNasc.setBounds(10, 295, 130, 17);

        lblIdade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblIdade.setText("Idade:");
        getContentPane().add(lblIdade);
        lblIdade.setBounds(250, 299, 40, 17);

        lblNacionalidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNacionalidade.setText("Nacionalidade:");
        getContentPane().add(lblNacionalidade);
        lblNacionalidade.setBounds(10, 385, 100, 24);

        lblNaturalidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNaturalidade.setText("Naturalidade:");
        getContentPane().add(lblNaturalidade);
        lblNaturalidade.setBounds(10, 440, 90, 17);

        txtNaturalidade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtNaturalidade);
        txtNaturalidade.setBounds(100, 430, 200, 36);

        lblEndUltCasa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEndUltCasa.setText("Endereço da última residência (Rua, Avenida):");
        getContentPane().add(lblEndUltCasa);
        lblEndUltCasa.setBounds(560, 205, 300, 17);

        txtEndUltCasa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtEndUltCasa);
        txtEndUltCasa.setBounds(860, 200, 352, 30);

        lblBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBairro.setText("Bairro:");
        getContentPane().add(lblBairro);
        lblBairro.setBounds(560, 246, 42, 17);

        lblMunicipio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMunicipio.setText("Município:");
        getContentPane().add(lblMunicipio);
        lblMunicipio.setBounds(560, 286, 63, 17);

        lblEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEstado.setText("Estado:");
        getContentPane().add(lblEstado);
        lblEstado.setBounds(860, 246, 50, 17);

        txtBairro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtBairro);
        txtBairro.setBounds(610, 240, 217, 30);

        txtMunicipio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtMunicipio);
        txtMunicipio.setBounds(630, 280, 217, 30);

        lblCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCep.setText("CEP:");
        getContentPane().add(lblCep);
        lblCep.setBounds(860, 280, 40, 30);

        txtNomeComp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtNomeComp);
        txtNomeComp.setBounds(120, 210, 430, 30);

        try {
            ftfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDataNasc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(ftfDataNasc);
        ftfDataNasc.setBounds(150, 290, 90, 30);

        try {
            ftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(ftfCep);
        ftfCep.setBounds(900, 280, 107, 30);

        try {
            ftfIdade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfIdade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(ftfIdade);
        ftfIdade.setBounds(290, 290, 36, 36);

        btnPaginaAnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPaginaAnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SetaE.png"))); // NOI18N
        btnPaginaAnt.setText("Etapa Anterior");
        btnPaginaAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaAntActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaginaAnt);
        btnPaginaAnt.setBounds(530, 610, 140, 40);

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        btnGravar.setLabel("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(680, 610, 90, 40);

        btnProxiPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProxiPag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Seta.png"))); // NOI18N
        btnProxiPag.setText("Próxima etapa");
        btnProxiPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxiPagActionPerformed(evt);
            }
        });
        getContentPane().add(btnProxiPag);
        btnProxiPag.setBounds(990, 610, 136, 40);

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(790, 610, 90, 40);

        cbxNacionalidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxNacionalidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Brasileiro", "Argentino", "Canadense", "Chileno", "Colombiano", "Cubano", "Norte-americano", "Mexicano", "Venezuelano", "Albanês", "Alemão", "Austríaco", "Belga", "Búlgaro", "Croata", "Cipriota", "Dinamarquês", "Eslovaco", "Esloveno", "Espanhol", "Francês", "Finlandês", "Grego", "Húngaro", "Iislandês", "Irlandês", "Italiano", "Kosovar", "Lituano", "Luxemburguês", "Montenegrino", "Holandês", "Norueguês", "Polaco", "Português", "Inglês", "Romeno", "Russo", "Sueco", "Suíço", "Turco", "Ucraniano", "Afegão", "Chinês", "Norte-coreano", "Sul-coreano", "Indiano", "Indoneso", "Iraniano", "Iraquiano", "Israelita", "Japonês", "Jordano", "Libanês", "Paquistanês", "Sírio", "Tailandês", "Timorense", "Vietnamita", "Sul-africano", "Argelino", "Angolano", "Cabo-verdiano", "Guineense", "Queniano", "Líbio", "Marroquino", "Moçambicano", "Nigeriano", "Ruandês", "Santomense", "Senegalês", "Somalí", "Sudanês", "Tunisino", "Australiano", "Neozelandês" }));
        getContentPane().add(cbxNacionalidade);
        cbxNacionalidade.setBounds(110, 380, 163, 34);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(890, 610, 90, 40);

        chbSemRegistro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chbSemRegistro.setText("Sem registro em cartório");
        getContentPane().add(chbSemRegistro);
        chbSemRegistro.setBounds(10, 180, 230, 18);

        chbIdadePresu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chbIdadePresu.setText("Idade Presumida");
        getContentPane().add(chbIdadePresu);
        chbIdadePresu.setBounds(330, 299, 128, 18);
        getContentPane().add(txtComoSerCha);
        txtComoSerCha.setBounds(210, 250, 280, 30);

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        getContentPane().add(cbEstado);
        cbEstado.setBounds(910, 240, 150, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1511-horz.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 1220, 770);

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1215, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        chbSemRegistro.setSelected(false);
        chbIdadePresu.setSelected(false);
        checkbox1.setState(false);
        checkbox2.setState(false);
        checkbox3.setState(false);
        checkbox4.setState(false);
        txtNomeComp.setText("");
        txtComoSerCha.setText("");
        cbxNacionalidade.setSelectedItem("Selecione");
        txtEndUltCasa.setText("");
        txtBairro.setText("");
        txtTransfDeServ.setText("");
        txtMunicipio.setText("");
        txtNaturalidade.setText("");
        cbxSexo.setSelectedItem("Selecione");
        cbxCorRaca.setSelectedItem("Selecione");
        cbEstado.setSelectedItem("Selecione");
        ftfCep.setText("");
        ftfDataNasc.setText("");
        ftfIdade.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed

        try {
            Connection con;

            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;
            sql = "INSERT INTO info_crianca_adolescente(Sem_Registro,Nome_Comp,Como_chamar,Sexo,Cor_raca,Nacionalidade,Naturalidade,Data_nasc,Idade,"
                    + "Idade_presu,End_ultima_resi,Bairro_ultima_resi,Muni_ultima_resi,Cep_ultima_resi,Estado_ultima_resi,Enc_vinda_muni_est,Uso_alcool_drogas,"
                    + "Defi_problema_grave,Acolhida_ant,Transferido_serv) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps;
            ps = (PreparedStatement) con.prepareStatement(sql);
            if (chbSemRegistro.isSelected()) {
                ps.setBoolean(1, true);
            } else {
                ps.setBoolean(1, false);
            }
            ps.setString(2, txtNomeComp.getText());
            ps.setString(3, txtComoSerCha.getText());
            ps.setString(4, cbxSexo.getSelectedItem().toString());
            ps.setString(5, cbxCorRaca.getSelectedItem().toString());
            ps.setString(6, cbxNacionalidade.getSelectedItem().toString());
            ps.setString(7, txtNaturalidade.getText());
            ps.setString(8, ftfDataNasc.getText());
            ps.setString(9, ftfIdade.getText());
            if (chbIdadePresu.isSelected()) {
                ps.setBoolean(10, true);
            } else {
                ps.setBoolean(10, false);
            }
            ps.setString(11, txtEndUltCasa.getText());
            ps.setString(12, txtBairro.getText());
            ps.setString(13, txtMunicipio.getText());
            ps.setString(14, ftfCep.getText());
            ps.setString(15, cbEstado.getSelectedItem().toString());
            ps.setBoolean(16, checkbox1.getState());
            ps.setBoolean(17, checkbox2.getState());
            ps.setBoolean(18, checkbox3.getState());
            ps.setBoolean(19, checkbox4.getState());
            ps.setString(20, txtTransfDeServ.getText());

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao salvar os dados!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQLException: ");
            JOptionPane.showMessageDialog(null, "SQLException: " + ex.getMessage() + "\nSQLState: " + ex.getSQLState()
                    + "\nVendorError: " + ex.getErrorCode());

        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnProxiPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxiPagActionPerformed
        JF_3CDA pnelso = new JF_3CDA();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnProxiPagActionPerformed

    private void btnPaginaAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaAntActionPerformed
        InformacoesGerais pnelso = new InformacoesGerais();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnPaginaAntActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu pnelso = new Menu();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfCA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPaginaAnt;
    private javax.swing.JButton btnProxiPag;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox cbxCorRaca;
    private javax.swing.JComboBox cbxNacionalidade;
    private javax.swing.JComboBox cbxSexo;
    private javax.swing.JCheckBox chbIdadePresu;
    private javax.swing.JCheckBox chbSemRegistro;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private java.awt.Checkbox checkbox4;
    private javax.swing.JFormattedTextField ftfCep;
    private javax.swing.JFormattedTextField ftfDataNasc;
    private javax.swing.JFormattedTextField ftfIdade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblComoSerCha;
    private javax.swing.JLabel lblCorRaca;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEndUltCasa;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNacionalidade;
    private javax.swing.JLabel lblNaturalidade;
    private javax.swing.JLabel lblNomeComp;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTransfServ;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtComoSerCha;
    private javax.swing.JTextField txtEndUltCasa;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNomeComp;
    private javax.swing.JTextField txtTransfDeServ;
    // End of variables declaration//GEN-END:variables
}
