/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacasulono;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Trentim
 */
public class InformacoesAdicionaisCrianca extends javax.swing.JFrame {

    /**
     * Creates new form InformacoesAdicionaisCrianca
     */
    public InformacoesAdicionaisCrianca() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chSim1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        chSim2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        chSim3 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        chAguardandoPretendente = new javax.swing.JCheckBox();
        chEstagioConvivencia = new javax.swing.JCheckBox();
        chSetencaJudicial = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        chSim7 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtQual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chSim8 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        chSim9 = new javax.swing.JCheckBox();
        chSemInformacao = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ftxtDataE = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        ftxtDataS = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAcolhimento = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesligamento = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        txtNomeeParentesco = new javax.swing.JTextField();
        cbParentesco = new javax.swing.JComboBox<>();
        btnGravar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnProx = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informações Adicionais Criança/Adolescente");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiniLogo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 300, 150);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Informações Adicionais Sobre a Criança/Adolescente ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 100, 620, 44);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Criança/adolescente sem família ou identidade conhecidas?:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 382, 17);

        chSim1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSim1.setText("Sim");
        getContentPane().add(chSim1);
        chSim1.setBounds(410, 150, 50, 18);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Incluido no Cadastro Nacional da criança ou adolescente desaparecido(CNCAD)?:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 519, 17);

        chSim2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSim2.setText("Sim");
        getContentPane().add(chSim2);
        chSim2.setBounds(540, 190, 45, 18);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("A criança/adolescente está incluído no Cadastro Nacional de adoção?:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 230, 446, 17);

        chSim3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSim3.setText("Sim");
        getContentPane().add(chSim3);
        chSim3.setBounds(470, 230, 50, 18);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Se ela/ele está incluída(o) no CNA, qual o estágio para adoção?:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 270, 409, 17);

        chAguardandoPretendente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chAguardandoPretendente.setText("Aguardando pretendente");
        getContentPane().add(chAguardandoPretendente);
        chAguardandoPretendente.setBounds(430, 270, 181, 18);

        chEstagioConvivencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chEstagioConvivencia.setText("Em estágio de convivência");
        getContentPane().add(chEstagioConvivencia);
        chEstagioConvivencia.setBounds(630, 270, 190, 18);

        chSetencaJudicial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSetencaJudicial.setText("Aguardando setença judicial para adoção");
        getContentPane().add(chSetencaJudicial);
        chSetencaJudicial.setBounds(840, 270, 300, 18);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Adolescente cumprindo média socioeducativo?:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(580, 150, 300, 17);

        chSim7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSim7.setText("Sim,");
        getContentPane().add(chSim7);
        chSim7.setBounds(880, 150, 49, 18);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Qual?:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(930, 150, 42, 17);
        getContentPane().add(txtQual);
        txtQual.setBounds(979, 145, 360, 28);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Criança/adolescente com histórico de rua?:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(600, 190, 274, 17);

        chSim8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSim8.setText("Sim");
        getContentPane().add(chSim8);
        chSim8.setBounds(880, 190, 60, 18);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("A criança/adolescente foi acolhida anteriormente?:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(580, 230, 320, 17);

        chSim9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSim9.setText("Sim");
        getContentPane().add(chSim9);
        chSim9.setBounds(900, 230, 45, 18);

        chSemInformacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chSemInformacao.setText("Sem Informação");
        getContentPane().add(chSemInformacao);
        chSemInformacao.setBounds(960, 230, 130, 18);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Em caso positivo, Informar os seguintes dados do serviço de acolhimento:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 310, 530, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Nome:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 345, 40, 17);
        getContentPane().add(txtNome);
        txtNome.setBounds(60, 340, 388, 28);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Endereço:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(460, 345, 65, 17);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(530, 340, 404, 28);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Data de Entrada:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(940, 345, 110, 17);

        try {
            ftxtDataE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftxtDataE);
        ftxtDataE.setBounds(1050, 340, 79, 28);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Data de Saída:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1140, 345, 94, 17);

        try {
            ftxtDataS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftxtDataS);
        ftxtDataS.setBounds(1240, 340, 79, 28);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Motivo do acolhimento:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 400, 145, 17);

        txtAcolhimento.setColumns(20);
        txtAcolhimento.setLineWrap(true);
        txtAcolhimento.setRows(5);
        txtAcolhimento.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAcolhimento);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 400, 285, 98);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Motivo do desligamento:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(520, 400, 160, 17);

        txtDesligamento.setColumns(20);
        txtDesligamento.setLineWrap(true);
        txtDesligamento.setRows(5);
        txtDesligamento.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtDesligamento);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(690, 400, 317, 98);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Nome e parentesco da pessoa que assumiu os cuidados/guarda após o desligamento:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 525, 545, 17);
        getContentPane().add(txtNomeeParentesco);
        txtNomeeParentesco.setBounds(560, 520, 308, 28);

        cbParentesco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1. Própria criança/adolescente acolhido ", "2.Mãe", "3.Pai  ", "4.Madrasta  ", "5.Padrasto  ", "6.Irmã(o) ", "7.Avó(ô)  ", "8.Tia(o) ", "9.Prima(o)   ", "10.Outros " }));
        getContentPane().add(cbParentesco);
        cbParentesco.setBounds(880, 520, 271, 30);

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(900, 580, 90, 40);

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(1000, 580, 90, 40);

        btnProx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Seta.png"))); // NOI18N
        btnProx.setText("Próxima etapa");
        btnProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxActionPerformed(evt);
            }
        });
        getContentPane().add(btnProx);
        btnProx.setBounds(1200, 580, 136, 40);

        btnAnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SetaE.png"))); // NOI18N
        btnAnt.setText("Etapa Anterior");
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnt);
        btnAnt.setBounds(750, 580, 140, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1100, 580, 90, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1511-horz.jpg"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 0, 1610, 910);

        setSize(new java.awt.Dimension(1348, 646));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        chAguardandoPretendente.setSelected(false);
        chEstagioConvivencia.setSelected(false);
        chSim1.setSelected(false);
        chSim2.setSelected(false);
        chSim3.setSelected(false);
        chSim7.setSelected(false);
        chSim8.setSelected(false);
        chSim9.setSelected(false);
        ftxtDataE.setText("");
        ftxtDataS.setText("");
        txtQual.setText("");
        chSemInformacao.setSelected(false);
        chSetencaJudicial.setSelected(false);
        txtAcolhimento.setText("");
        txtDesligamento.setText("");
        txtNome.setText("");
        txtNomeeParentesco.setText("");
        txtEndereco.setText("");
        cbParentesco.setSelectedItem("Selecione");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try {
            /*Connection - classe usada para estabelecer uma conexão com o banco. Neste momento devemos informar
             o endereço do servidor(IP) o nome do Banco e o usuário e nenha de acesso   */
            Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;// String para receber a Scrip(O comando SQL que será usado-Insert/Update/DLETE)
            sql = "INSERT INTO inf_ad_crian_adole(Crian_adoles_sem_fam_ou_ident_con,Inc_n_cad_nac_d_crian_ou_adole_desap,A_crian_adole_est_incl_no_cad_nac_d_ado,"
                    + "Aguardando_Pretendente,Em_Estagio_de_convivencia,Aguard_Sent_Jud_p_Adoc,Adole_cum_med_socioed,Qual,crian_adole_com_hist_d_sit_d_r,A_crian_adole_f_acol_ant,"
                    + "Sem_Informacao,Nome_Completo,Endereco,Dat_d_Ent,Dat_d_Sai,Mot_d_Acolhi,Mot_d_Desl,Nome_e_Parentesco,Parentesco)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            /*uma forma de você fazer uma inserção no banco mais segura,
             onde você prepara os parametros para serem inseridos */
            PreparedStatement ps;
            ps = (PreparedStatement) con.prepareStatement(sql);
            if (chSim1.isSelected()) {
                ps.setBoolean(1, true);
            } else {
                ps.setBoolean(1, false);
            }

            if (chSim2.isSelected()) {
                ps.setBoolean(2, true);
            } else {
                ps.setBoolean(2, false);
            }

            if (chSim3.isSelected()) {
                ps.setBoolean(3, true);
            } else {
                ps.setBoolean(3, false);
            }

            if (chAguardandoPretendente.isSelected()) {
                ps.setBoolean(4, true);
            } else {
                ps.setBoolean(4, false);
            }

            if (chEstagioConvivencia.isSelected()) {
                ps.setBoolean(5, true);
            } else {
                ps.setBoolean(5, false);
            }

            if (chSetencaJudicial.isSelected()) {
                ps.setBoolean(6, true);
            } else {
                ps.setBoolean(6, false);
            }

            if (chSim7.isSelected()) {
                ps.setBoolean(7, true);
            } else {
                ps.setBoolean(7, false);
            }

            ps.setString(8, txtQual.getText());

            if (chSim8.isSelected()) {
                ps.setBoolean(9, true);
            } else {
                ps.setBoolean(9, false);
            }

            if (chSim9.isSelected()) {
                ps.setBoolean(10, true);
            } else {
                ps.setBoolean(10, false);
            }
            if (chSemInformacao.isSelected()) {
                ps.setBoolean(11, true);
            } else {
                ps.setBoolean(11, false);
            }
            ps.setString(12, txtNome.getText());
            ps.setString(13, txtEndereco.getText());
            ps.setString(14, ftxtDataE.getText());
            ps.setString(15, ftxtDataS.getText());
            ps.setString(16, txtAcolhimento.getText());
            ps.setString(17, txtDesligamento.getText());
            ps.setString(18, txtNomeeParentesco.getText());
            ps.setString(19, cbParentesco.getSelectedItem().toString());

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Falha no Cadastro");
            }
        } catch (SQLException ex)//Se ocorrer algum erro uma mensagem é exibida.
        {
            JOptionPane.showMessageDialog(null, "SQLException: ");
            JOptionPane.showMessageDialog(null, "SQLException: " + ex.getMessage() + "\nSQLState: " + ex.getSQLState()
                    + "\nVendorError: " + ex.getErrorCode());
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxActionPerformed
        Irmaos_7 pnelso = new Irmaos_7();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnProxActionPerformed

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        InformacoesAdicionaisFamilia pnelso = new InformacoesAdicionaisFamilia();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnAntActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu pnelso = new Menu();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacoesAdicionaisCrianca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacoesAdicionaisCrianca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacoesAdicionaisCrianca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacoesAdicionaisCrianca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacoesAdicionaisCrianca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnProx;
    private javax.swing.JComboBox<String> cbParentesco;
    private javax.swing.JCheckBox chAguardandoPretendente;
    private javax.swing.JCheckBox chEstagioConvivencia;
    private javax.swing.JCheckBox chSemInformacao;
    private javax.swing.JCheckBox chSetencaJudicial;
    private javax.swing.JCheckBox chSim1;
    private javax.swing.JCheckBox chSim2;
    private javax.swing.JCheckBox chSim3;
    private javax.swing.JCheckBox chSim7;
    private javax.swing.JCheckBox chSim8;
    private javax.swing.JCheckBox chSim9;
    private javax.swing.JFormattedTextField ftxtDataE;
    private javax.swing.JFormattedTextField ftxtDataS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAcolhimento;
    private javax.swing.JTextArea txtDesligamento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeeParentesco;
    private javax.swing.JTextField txtQual;
    // End of variables declaration//GEN-END:variables
}
