/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacasulono;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Trentim
 */
public class InformacoesAdicionaisFamilia extends javax.swing.JFrame {

    /**
     * Creates new form InformacoesAdicionaisFamilia
     */
    public InformacoesAdicionaisFamilia() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chSim1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtTranstornoMental = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        chSim2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtDependencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        chSim3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtPessoaDeficiencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        chSim4 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtFamInd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chSim5 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        txtCumprimentoMSE = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        chSim6 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        txtSituacaoRua = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEspecificidade1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEspeciQuantas1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtEspecificidade2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbProgramaSocial = new javax.swing.JComboBox<>();
        chBolsaFamilia = new javax.swing.JCheckBox();
        chPeti = new javax.swing.JCheckBox();
        chBPCFam = new javax.swing.JCheckBox();
        chBPCCrian = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtEspecifiQuantas2 = new javax.swing.JTextField();
        btnProx = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiniLogo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 330, 147);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Informações adicionais sobre a família");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 130, 460, 32);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Possui alguém na família que tem/sofre de:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 200, 310, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Transtorno mental/sofrimento psíquico:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 235, 241, 17);

        chSim1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chSim1.setText("Sim,");
        getContentPane().add(chSim1);
        chSim1.setBounds(320, 235, 48, 18);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantas?:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 235, 63, 17);
        getContentPane().add(txtTranstornoMental);
        txtTranstornoMental.setBounds(440, 230, 57, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Dependência quimíca:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(610, 235, 134, 17);

        chSim2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chSim2.setText("Sim,");
        getContentPane().add(chSim2);
        chSim2.setBounds(750, 235, 48, 18);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quantas?:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(810, 235, 63, 17);
        getContentPane().add(txtDependencia);
        txtDependencia.setBounds(880, 230, 57, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pessoa com deficiência:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 295, 143, 17);

        chSim3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chSim3.setText("Sim,");
        getContentPane().add(chSim3);
        chSim3.setBounds(220, 295, 48, 18);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Quantas?:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 295, 63, 17);
        getContentPane().add(txtPessoaDeficiencia);
        txtPessoaDeficiencia.setBounds(340, 290, 57, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Família/Indivíduo indígena:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(610, 295, 159, 17);

        chSim4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chSim4.setText("Sim,");
        getContentPane().add(chSim4);
        chSim4.setBounds(780, 295, 48, 18);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Quantas?:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(830, 295, 63, 17);
        getContentPane().add(txtFamInd);
        txtFamInd.setBounds(900, 290, 57, 28);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Pessoa presa ou em  cumprimento de MSE:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 355, 266, 17);

        chSim5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chSim5.setText("Sim,");
        getContentPane().add(chSim5);
        chSim5.setBounds(340, 355, 48, 18);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Quantas?:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(390, 355, 63, 17);
        getContentPane().add(txtCumprimentoMSE);
        txtCumprimentoMSE.setBounds(460, 350, 57, 28);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Em situação de rua:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(610, 355, 122, 17);

        chSim6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chSim6.setText("Sim,");
        getContentPane().add(chSim6);
        chSim6.setBounds(740, 355, 48, 18);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Quantas?:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(790, 355, 63, 17);
        getContentPane().add(txtSituacaoRua);
        txtSituacaoRua.setBounds(860, 350, 57, 28);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Outra especificidade 1:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(70, 415, 144, 17);
        getContentPane().add(txtEspecificidade1);
        txtEspecificidade1.setBounds(220, 410, 182, 28);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Quantas?:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(410, 415, 63, 17);
        getContentPane().add(txtEspeciQuantas1);
        txtEspeciQuantas1.setBounds(480, 410, 57, 28);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Outra especificidade 2:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(610, 415, 138, 17);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Quantas?:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(950, 415, 63, 17);
        getContentPane().add(txtEspecificidade2);
        txtEspecificidade2.setBounds(760, 410, 182, 28);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setText("Programa e benefícios sociais");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(360, 450, 350, 32);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("A família recebe dinheiro de algum programa social?:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(210, 498, 335, 17);

        cbProgramaSocial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbProgramaSocial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));
        getContentPane().add(cbProgramaSocial);
        cbProgramaSocial.setBounds(550, 490, 105, 30);

        chBolsaFamilia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chBolsaFamilia.setText("Bolsa Família");
        getContentPane().add(chBolsaFamilia);
        chBolsaFamilia.setBounds(260, 530, 96, 18);

        chPeti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chPeti.setText("PETI");
        getContentPane().add(chPeti);
        chPeti.setBounds(440, 530, 50, 18);

        chBPCFam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chBPCFam.setText("BPC(Pessoa da família)");
        getContentPane().add(chBPCFam);
        chBPCFam.setBounds(260, 580, 158, 18);

        chBPCCrian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chBPCCrian.setText("BPC(Criança/Adolescente)");
        getContentPane().add(chBPCCrian);
        chBPCCrian.setBounds(440, 580, 180, 18);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Recebe de outro programa social? Digite o nome:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(210, 615, 303, 17);
        getContentPane().add(txtNome);
        txtNome.setBounds(520, 610, 480, 28);

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(700, 660, 90, 40);

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(800, 660, 90, 40);
        getContentPane().add(txtEspecifiQuantas2);
        txtEspecifiQuantas2.setBounds(1018, 410, 57, 28);

        btnProx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Seta.png"))); // NOI18N
        btnProx.setText("Próxima Etapa");
        btnProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxActionPerformed(evt);
            }
        });
        getContentPane().add(btnProx);
        btnProx.setBounds(1010, 660, 140, 40);

        btnAnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SetaE.png"))); // NOI18N
        btnAnt.setText("Etapa Anterior");
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnt);
        btnAnt.setBounds(550, 660, 135, 40);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(900, 660, 100, 40);

        lblFundo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1511-horz.jpg"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1490, 860);

        setSize(new java.awt.Dimension(1159, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText("");
        txtEspecificidade1.setText("");
        txtEspecificidade2.setText("");
        chBPCFam.setSelected(false);
        chBPCCrian.setSelected(false);
        chBolsaFamilia.setSelected(false);
        chPeti.setSelected(false);
        cbProgramaSocial.setSelectedItem("Selecione");
        chSim1.setSelected(false);
        chSim2.setSelected(false);
        chSim3.setSelected(false);
        chSim4.setSelected(false);
        chSim5.setSelected(false);
        chSim6.setSelected(false);
        txtEspeciQuantas1.setText("");
        txtEspecifiQuantas2.setText("");
        txtFamInd.setText("");
        txtPessoaDeficiencia.setText("");
        txtDependencia.setText("");
        txtCumprimentoMSE.setText("");
        txtTranstornoMental.setText("");
        txtSituacaoRua.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try {
            /*Connection - classe usada para estabelecer uma conexão com o banco. Neste momento devemos informar
             o endereço do servidor(IP) o nome do Banco e o usuário e nenha de acesso   */
            Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;// String para receber a Scrip(O comando SQL que será usado-Insert/Update/DLETE)
            sql = "INSERT INTO programas_e_beneficios_sociais(A_fam_rec_din_d_alg_program_soc,Bolsa_Familia,PETI,BPC_pessoa_da_familia,"
                    + "BPC_crianca_adolescente_acolhido,Outro_Qual)VALUES(?,?,?,?,?,?)";
            /*uma forma de você fazer uma inserção no banco mais segura,
             onde você prepara os parametros para serem inseridos */
            PreparedStatement ps;
            ps = (PreparedStatement) con.prepareStatement(sql);

            ps.setString(1, cbProgramaSocial.getSelectedItem().toString());

            if (chBolsaFamilia.isSelected()) {
                ps.setBoolean(2, true);
            } else {
                ps.setBoolean(2, false);
            }

            if (chPeti.isSelected()) {
                ps.setBoolean(3, true);
            } else {
                ps.setBoolean(3, false);
            }

            if (chBPCFam.isSelected()) {
                ps.setBoolean(4, true);
            } else {
                ps.setBoolean(4, false);
            }

            if (chBPCCrian.isSelected()) {
                ps.setBoolean(5, true);
            } else {
                ps.setBoolean(5, false);
            }

            ps.setString(6, txtNome.getText());

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Falha no Cadastro");
            }
        } catch (SQLException ex)//Se ocorrer algum erro uma mensagem é exibida.
        {
            JOptionPane.showMessageDialog(null, "SQLException: ");
            JOptionPane.showMessageDialog(null, "SQLException: " + ex.getMessage() + "\nSQLState: " + ex.getSQLState()
                    + "\nVendorError: " + ex.getErrorCode());
        }
        try {
            /*Connection - classe usada para estabelecer uma conexão com o banco. Neste momento devemos informar
             o endereço do servidor(IP) o nome do Banco e o usuário e nenha de acesso   */
            Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;// String para receber a Scrip(O comando SQL que será usado-Insert/Update/DLETE)
            sql = "INSERT INTO inf_ad_sob_a_fam(Transtorno_Mental,Tm_Quantidade,Dependencia_quimica,Dq_Quantidade,Pessoa_com_deficiencia,Pcd_Quantidade,Familia_Individuo_indigena,"
                    + "Fii_Quantidade,Pessoa_presa_ou_em_cumprimento,PPC_Quantidade,Em_situacao_de_rua,ESDR_Quantidade,Outra_especificidade,OE_Quantidade,Outra_especificidades,"
                    + "OEP_Quantidade)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            /*uma forma de você fazer uma inserção no banco mais segura,
             onde você prepara os parametros para serem inseridos */
            PreparedStatement ps;
            ps = (PreparedStatement) con.prepareStatement(sql);
            if (chSim1.isSelected()) {
                ps.setBoolean(1, true);
            } else {
                ps.setBoolean(1, false);
            }
            ps.setString(2, txtTranstornoMental.getText());

            if (chSim2.isSelected()) {
                ps.setBoolean(3, true);
            } else {
                ps.setBoolean(3, false);
            }
            ps.setString(4, txtDependencia.getText());

            if (chSim3.isSelected()) {
                ps.setBoolean(5, true);
            } else {
                ps.setBoolean(5, false);
            }
            ps.setString(6, txtPessoaDeficiencia.getText());

            if (chSim4.isSelected()) {
                ps.setBoolean(7, true);
            } else {
                ps.setBoolean(7, false);
            }
            ps.setString(8, txtFamInd.getText());

            if (chSim5.isSelected()) {
                ps.setBoolean(9, true);
            } else {
                ps.setBoolean(9, false);
            }
            ps.setString(10, txtCumprimentoMSE.getText());

            if (chSim6.isSelected()) {
                ps.setBoolean(11, true);
            } else {
                ps.setBoolean(11, false);
            }
            ps.setString(12, txtSituacaoRua.getText());

            ps.setString(13, txtEspecificidade1.getText());
            ps.setString(14, txtEspeciQuantas1.getText());
            ps.setString(15, txtEspecificidade2.getText());
            ps.setString(16, txtEspecifiQuantas2.getText());

            int res = ps.executeUpdate();
            if (res > 0) {
            } else {
                JOptionPane.showMessageDialog(null, "Falha no Cadastro");
            }
        } catch (SQLException ex)//Se ocorrer algum erro uma mensagem é exibida.
        {
            JOptionPane.showMessageDialog(null, "SQLException: ");
            JOptionPane.showMessageDialog(null, "SQLException: " + ex.getMessage() + "\nSQLState: " + ex.getSQLState()
                    + "\nVendorError: " + ex.getErrorCode());
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxActionPerformed
        InformacoesAdicionaisCrianca pnelso = new InformacoesAdicionaisCrianca();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnProxActionPerformed

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        ComposicaoFamiliar pnelso = new ComposicaoFamiliar();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnAntActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu pnelso = new Menu();
        pnelso.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacoesAdicionaisFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacoesAdicionaisFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacoesAdicionaisFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacoesAdicionaisFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacoesAdicionaisFamilia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnProx;
    private javax.swing.JComboBox<String> cbProgramaSocial;
    private javax.swing.JCheckBox chBPCCrian;
    private javax.swing.JCheckBox chBPCFam;
    private javax.swing.JCheckBox chBolsaFamilia;
    private javax.swing.JCheckBox chPeti;
    private javax.swing.JCheckBox chSim1;
    private javax.swing.JCheckBox chSim2;
    private javax.swing.JCheckBox chSim3;
    private javax.swing.JCheckBox chSim4;
    private javax.swing.JCheckBox chSim5;
    private javax.swing.JCheckBox chSim6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JTextField txtCumprimentoMSE;
    private javax.swing.JTextField txtDependencia;
    private javax.swing.JTextField txtEspeciQuantas1;
    private javax.swing.JTextField txtEspecifiQuantas2;
    private javax.swing.JTextField txtEspecificidade1;
    private javax.swing.JTextField txtEspecificidade2;
    private javax.swing.JTextField txtFamInd;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPessoaDeficiencia;
    private javax.swing.JTextField txtSituacaoRua;
    private javax.swing.JTextField txtTranstornoMental;
    // End of variables declaration//GEN-END:variables
}
