/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacasulono;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author GMNascimento-Inf181
 */
public class Irmaos_7 extends javax.swing.JFrame {

    /**
     * Creates new form Irmaos_7
     */
    public Irmaos_7() {

        getContentPane().setBackground(Color.white);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ResideNome = new javax.swing.JTextField();
        ResideIdade = new javax.swing.JTextField();
        ResideNomeParen = new javax.swing.JTextField();
        ResideParen = new javax.swing.JTextField();
        ResideEnd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        PossuiNome = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PossuiIdade = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        OutroEndSerAco = new javax.swing.JTextField();
        OutroNome = new javax.swing.JTextField();
        OutroIdade = new javax.swing.JTextField();
        OutroServicoAco = new javax.swing.JTextField();
        OutroTecRespon = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        QuantosIrmaos = new javax.swing.JTextField();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        FalecidoNome = new javax.swing.JTextField();
        FalecidoCausa = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblMiniLogo = new javax.swing.JLabel();
        btnFim = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NaoFoiAcolhido = new javax.swing.JTextArea();
        ResideSexo = new javax.swing.JComboBox<>();
        ResideTel = new javax.swing.JFormattedTextField();
        PossuiSexo = new javax.swing.JComboBox<>();
        PossuiDataAco = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PossuiMotivoAco = new javax.swing.JTextArea();
        OutroSexo = new javax.swing.JComboBox<>();
        OutroDataAco = new javax.swing.JFormattedTextField();
        FalecidoDataNasc = new javax.swing.JFormattedTextField();
        FalecidoDataFaleci = new javax.swing.JFormattedTextField();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("INFORMAÇÕES SOBRE IRMÃOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 20, 390, 32);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("<html> A criança/adolescente possui irmão(s) que reside(m) com a família natural, família extensa ou pessoa sem parentesco? ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 150, 430, 30);

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1.setText("Sim");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(460, 420, 45, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("<html> Em caso positivo, informe os dados das pessoas com quem o(s) irmão(s) reside(m), para o campo parentesco utilizar os códigos do item 4: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 470, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 245, 40, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Sexo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(155, 285, 35, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Idade:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 285, 39, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Nome do parente:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 320, 113, 17);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Parentesco:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 285, 76, 19);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Endereço:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 355, 65, 19);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Telefone:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 395, 60, 19);

        ResideNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(ResideNome);
        ResideNome.setBounds(50, 240, 320, 30);

        ResideIdade.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(ResideIdade);
        ResideIdade.setBounds(50, 280, 100, 30);

        ResideNomeParen.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(ResideNomeParen);
        ResideNomeParen.setBounds(130, 315, 400, 30);

        ResideParen.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(ResideParen);
        ResideParen.setBounds(390, 280, 102, 30);

        ResideEnd.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(ResideEnd);
        ResideEnd.setBounds(130, 350, 400, 30);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 150, 270, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("<html> A criança/adolescente possui irmão(s) neste serviço de acolhimento? ,Em caso positivo, informe os dados do(s) irmão(s) na tabela a seguir:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 420, 450, 50);

        jCheckBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox2.setText("Sim");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(350, 160, 45, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Nome:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 470, 40, 30);

        PossuiNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(PossuiNome);
        PossuiNome.setBounds(50, 470, 210, 30);

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Sexo:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(270, 475, 35, 19);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("Idade:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 515, 39, 19);

        PossuiIdade.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(PossuiIdade);
        PossuiIdade.setBounds(50, 510, 102, 30);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setText("Data do acolhimento:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(160, 515, 140, 19);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Motivo do acolhimento:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 550, 160, 17);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("<html>A criança/adolescente possui irmão(s) em outro(s) serviço(s) de acolhimento?,Em caso positivo, justifique por que o grupo de irmãos não foi acolhido no mesmo serviço de acolhimento:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(700, 70, 400, 60);

        jCheckBox3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox3.setText("Sim");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(1100, 90, 60, 20);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("<html>Informações do(s) irmão(s) que está/estão acolhido(s) em outro(s) serviço(s) de acolhimento:");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(710, 230, 360, 50);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Nome:");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(680, 285, 40, 14);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Sexo:");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(1060, 285, 40, 20);

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel25.setText("Idade:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(680, 315, 40, 14);

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setText("Data de acolimento:");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(840, 315, 130, 19);

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel27.setText("Nome do Serviço de Acolhimento:");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(560, 345, 220, 19);

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel28.setText("Endereço do Serviço de Acolhimento:");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(540, 375, 240, 19);

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel29.setText("Técnico responsável:");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(640, 405, 140, 19);

        OutroEndSerAco.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(OutroEndSerAco);
        OutroEndSerAco.setBounds(780, 370, 320, 30);

        OutroNome.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(OutroNome);
        OutroNome.setBounds(730, 280, 320, 30);

        OutroIdade.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(OutroIdade);
        OutroIdade.setBounds(730, 310, 100, 30);

        OutroServicoAco.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(OutroServicoAco);
        OutroServicoAco.setBounds(780, 340, 320, 30);

        OutroTecRespon.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(OutroTecRespon);
        OutroTecRespon.setBounds(780, 400, 320, 30);

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel31.setText("<html>A criança/adolescente possui irmão(s) que foi/foram adotado(s)?,Se sim, quantos irmãos foram adotados? ");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(610, 430, 350, 50);

        jCheckBox4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox4.setText("Sim");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(950, 490, 45, 20);

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel32.setText("<html>A criança/adolescente possui irmão(s) falecido(s)?, Em caso positivo, informe os dados do(s) irmão(s) falecidos na tabela a seguir:");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(610, 480, 340, 60);

        QuantosIrmaos.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(QuantosIrmaos);
        QuantosIrmaos.setBounds(1000, 440, 80, 30);

        jCheckBox5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jCheckBox5.setText("Sim");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(950, 435, 45, 40);

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabel34);
        jLabel34.setBounds(670, 600, 270, 0);

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel35.setText("Nome:");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(580, 545, 40, 19);

        jLabel36.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel36.setText("Data de Nascimento:");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(945, 545, 140, 19);

        jLabel37.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel37.setText("Data De Falecimento:");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(490, 585, 140, 19);

        jLabel38.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel38.setText("Causa Do Falecimento:");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(730, 585, 150, 19);

        FalecidoNome.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(FalecidoNome);
        FalecidoNome.setBounds(630, 540, 310, 30);

        FalecidoCausa.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        getContentPane().add(FalecidoCausa);
        FalecidoCausa.setBounds(880, 580, 310, 30);

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(900, 615, 90, 40);

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(1000, 615, 90, 40);

        lblMiniLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiniLogo.png"))); // NOI18N
        getContentPane().add(lblMiniLogo);
        lblMiniLogo.setBounds(0, 0, 300, 140);

        btnFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ok.png"))); // NOI18N
        btnFim.setText("Finalizar");
        btnFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFimActionPerformed(evt);
            }
        });
        getContentPane().add(btnFim);
        btnFim.setBounds(1100, 615, 94, 40);

        btnAnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SetaE.png"))); // NOI18N
        btnAnt.setText("Etapa Anterior");
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnt);
        btnAnt.setBounds(740, 615, 140, 40);

        NaoFoiAcolhido.setColumns(20);
        NaoFoiAcolhido.setLineWrap(true);
        NaoFoiAcolhido.setRows(5);
        NaoFoiAcolhido.setWrapStyleWord(true);
        jScrollPane2.setViewportView(NaoFoiAcolhido);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(700, 130, 380, 100);

        ResideSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "M - Masculino", "F - Feminino" }));
        getContentPane().add(ResideSexo);
        ResideSexo.setBounds(190, 280, 100, 26);

        try {
            ResideTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ResideTel);
        ResideTel.setBounds(130, 390, 120, 28);

        PossuiSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PossuiSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "M - Masculino", "F - Feminino" }));
        getContentPane().add(PossuiSexo);
        PossuiSexo.setBounds(310, 470, 100, 30);

        try {
            PossuiDataAco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(PossuiDataAco);
        PossuiDataAco.setBounds(300, 510, 100, 28);

        PossuiMotivoAco.setColumns(20);
        PossuiMotivoAco.setLineWrap(true);
        PossuiMotivoAco.setRows(5);
        PossuiMotivoAco.setWrapStyleWord(true);
        jScrollPane1.setViewportView(PossuiMotivoAco);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 570, 320, 110);

        OutroSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        OutroSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "M - Masculino", "F - Feminino" }));
        getContentPane().add(OutroSexo);
        OutroSexo.setBounds(1100, 280, 100, 27);

        try {
            OutroDataAco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(OutroDataAco);
        OutroDataAco.setBounds(970, 310, 100, 28);

        try {
            FalecidoDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(FalecidoDataNasc);
        FalecidoDataNasc.setBounds(1080, 540, 90, 28);

        try {
            FalecidoDataFaleci.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(FalecidoDataFaleci);
        FalecidoDataFaleci.setBounds(630, 580, 90, 28);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1511-horz.jpg"))); // NOI18N
        Fundo.setText("jLabel30");
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 1680, 870);

        setSize(new java.awt.Dimension(1223, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        //inserir//
        try {
            /*Connection - classe usada para estabelecer uma conexão com o banco. Neste momento devemos informar
            o endereço do servidor(IP) o nome do Banco e o usuário e nenha de acesso   */
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;// String para receber a Scrip(O comando SQL que será usado-Insert/Update/DLETE)
            sql = "INSERT INTO irmaos_7(Sem_Parentesco,Nome_Reside,Sexo_Reside,Idade_Reside,Nome_do_parente_Reside,Parentesco_Reside,Endereco_Reside,"
                    + "Telefone_Reside,Irmaos_nesse_Acolhimento,Nome_Possui,Sexo_Possui,Idade_Possui,Data_do_acohimento_Possui,Motivo_do_acolhimento_Possui,"
                    + "Possui_Irmaos_em_outro_acolhimento,Nao_foi_Acolhido,Outro_Nome,Outro_Sexo,Outro_Idade,Outro_Data_de_Acolhimento,Outro_Nome_do_Servico_Acolhimento,Outro_Endereco_do_Servico_Acolhimento,"
                    + "Outro_Tecnico_Responsavel,Irmaos_Adotado,Quantos_Irmaos,Irmao_Falecido,Falecido_Nome,Falecido_Data_Nascimento,Falecido_Data_Falecimento,Falecido_Causa_Falecimento) "
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            /*uma forma de você fazer uma inserção no banco mais segura,
            onde você prepara os parametros para serem inseridos */
            PreparedStatement ps;
            ps = con.prepareStatement(sql);
            if (jCheckBox2.isSelected()) {
                ps.setBoolean(1, true);
            } else {
                ps.setBoolean(1, false);
            }
            ps.setString(2, ResideNome.getText());
            ps.setString(3, ResideSexo.getSelectedItem().toString());
            ps.setString(4, ResideIdade.getText());
            ps.setString(5, ResideNomeParen.getText());
            ps.setString(6, ResideParen.getText());
            ps.setString(7, ResideEnd.getText());
            ps.setString(8, ResideTel.getText());
            if (jCheckBox1.isSelected()) {
                ps.setBoolean(9, true);
            } else {
                ps.setBoolean(9, false);
            }
            ps.setString(10, PossuiNome.getText());
            ps.setString(11, PossuiSexo.getSelectedItem().toString());
            ps.setString(12, PossuiIdade.getText());
            ps.setString(13, PossuiDataAco.getText());
            ps.setString(14, PossuiMotivoAco.getText());
            if (jCheckBox3.isSelected()) {
                ps.setBoolean(15, true);
            } else {
                ps.setBoolean(15, false);
            }
            ps.setString(16, NaoFoiAcolhido.getText());
            ps.setString(17, OutroNome.getText());
            ps.setString(18, OutroSexo.getSelectedItem().toString());
            ps.setString(19, OutroIdade.getText());
            ps.setString(20, OutroDataAco.getText());
            ps.setString(21, OutroServicoAco.getText());
            ps.setString(22, OutroEndSerAco.getText());
            ps.setString(23, OutroTecRespon.getText());
            if (jCheckBox5.isSelected()) {
                ps.setBoolean(24, true);
            } else {
                ps.setBoolean(24, false);
            }
            ps.setString(25, QuantosIrmaos.getText());
            if (jCheckBox4.isSelected()) {
                ps.setBoolean(26, true);
            } else {
                ps.setBoolean(26, false);
            }
            ps.setString(27, FalecidoNome.getText());
            ps.setString(28, FalecidoDataNasc.getText());
            ps.setString(29, FalecidoDataFaleci.getText());
            ps.setString(30, FalecidoCausa.getText());

            /* A Script é executada e se retornar algo significa que ocorreu com sucesso*/
            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Falha no Cadastro");
            }
        } catch (SQLException ex)//Se ocorrer algum erro uma mensagem é exibida.
        {
            JOptionPane.showMessageDialog(null, "SQLException: ");
            JOptionPane.showMessageDialog(null, "SQLException: " + ex.getMessage() + "\nSQLState: " + ex.getSQLState()
                    + "\nVendorError: " + ex.getErrorCode());
        }

    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        ResideNome.setText("");
        ResideSexo.setSelectedItem("Selecione");
        ResideIdade.setText("");
        ResideNomeParen.setText("");
        ResideParen.setText("");
        ResideEnd.setText("");
        ResideTel.setText("");
        NaoFoiAcolhido.setText("");
        OutroNome.setText("");
        OutroSexo.setSelectedItem("Selecione");
        OutroIdade.setText("");
        OutroDataAco.setText("");
        OutroServicoAco.setText("");
        OutroEndSerAco.setText("");
        OutroTecRespon.setText("");
        FalecidoNome.setText("");
        FalecidoDataNasc.setText("");
        FalecidoDataFaleci.setText("");
        FalecidoCausa.setText("");
        PossuiNome.setText("");
        PossuiSexo.setSelectedItem("Selecione");
        PossuiIdade.setText("");
        PossuiDataAco.setText("");
        PossuiMotivoAco.setText("");
        QuantosIrmaos.setText("");

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFimActionPerformed
        Menu pnelso = new Menu();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnFimActionPerformed

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        InformacoesAdicionaisCrianca pnelso = new InformacoesAdicionaisCrianca();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnAntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Irmaos_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Irmaos_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Irmaos_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Irmaos_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Irmaos_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FalecidoCausa;
    private javax.swing.JFormattedTextField FalecidoDataFaleci;
    private javax.swing.JFormattedTextField FalecidoDataNasc;
    private javax.swing.JTextField FalecidoNome;
    private javax.swing.JLabel Fundo;
    private javax.swing.JTextArea NaoFoiAcolhido;
    private javax.swing.JFormattedTextField OutroDataAco;
    private javax.swing.JTextField OutroEndSerAco;
    private javax.swing.JTextField OutroIdade;
    private javax.swing.JTextField OutroNome;
    private javax.swing.JTextField OutroServicoAco;
    private javax.swing.JComboBox<String> OutroSexo;
    private javax.swing.JTextField OutroTecRespon;
    private javax.swing.JFormattedTextField PossuiDataAco;
    private javax.swing.JTextField PossuiIdade;
    private javax.swing.JTextArea PossuiMotivoAco;
    private javax.swing.JTextField PossuiNome;
    private javax.swing.JComboBox<String> PossuiSexo;
    private javax.swing.JTextField QuantosIrmaos;
    private javax.swing.JTextField ResideEnd;
    private javax.swing.JTextField ResideIdade;
    private javax.swing.JTextField ResideNome;
    private javax.swing.JTextField ResideNomeParen;
    private javax.swing.JTextField ResideParen;
    private javax.swing.JComboBox<String> ResideSexo;
    private javax.swing.JFormattedTextField ResideTel;
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnFim;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMiniLogo;
    // End of variables declaration//GEN-END:variables
}
