/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacasulono;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author GMNascimento-Inf181
 */
public class JF_3CDA extends javax.swing.JFrame {

    /**
     * Creates new form JF_3CDA
     */
    public JF_3CDA() {

        getContentPane().setBackground(Color.white);
        initComponents();
        //JF_3CDA.setBackgroundImage(new Image ("./Imagens/Koala.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNomerespon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFuncResp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chEntregaVoluntaria = new javax.swing.JCheckBox();
        chViolenciaFisica = new javax.swing.JCheckBox();
        chExploracaoSexual = new javax.swing.JCheckBox();
        chAmeacaMorte = new javax.swing.JCheckBox();
        chPaisResponsaveis = new javax.swing.JCheckBox();
        chOrfandade = new javax.swing.JCheckBox();
        chViolenciaPsicologica = new javax.swing.JCheckBox();
        chTrabalhoInfantil = new javax.swing.JCheckBox();
        chAusenciaDosPaisPrisao = new javax.swing.JCheckBox();
        chAbandono = new javax.swing.JCheckBox();
        chAbusoSexual = new javax.swing.JCheckBox();
        chAusenciaResponsaveis = new javax.swing.JCheckBox();
        chPaisDeficiencia = new javax.swing.JCheckBox();
        chConflitoFamiliar = new javax.swing.JCheckBox();
        chPaisTranstornoMental = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chMae = new javax.swing.JCheckBox();
        chPai = new javax.swing.JCheckBox();
        chMadrastra = new javax.swing.JCheckBox();
        chPadrasto = new javax.swing.JCheckBox();
        chIrmao = new javax.swing.JCheckBox();
        chTio = new javax.swing.JCheckBox();
        chPrimo = new javax.swing.JCheckBox();
        chAvo = new javax.swing.JCheckBox();
        chNaoSeAplica = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnProx = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtnomecompletoeparen = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEspecifique = new javax.swing.JTextArea();
        txtContato = new javax.swing.JFormattedTextField();
        chPaisResponsaveisDrogas = new javax.swing.JCheckBox();
        chNegligencia = new javax.swing.JCheckBox();
        txtOutQual = new javax.swing.JTextField();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiniLogo.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 350, 150);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nome do responsável pelo acolhimento:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 173, 252, 20);

        txtNomerespon.setText("\n");
        getContentPane().add(txtNomerespon);
        txtNomerespon.setBounds(270, 170, 313, 28);
        txtNomerespon.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Função do responsável pelo acolhimento:\n");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(5, 213, 264, 20);

        txtFuncResp.setText("\n");
        getContentPane().add(txtFuncResp);
        txtFuncResp.setBounds(270, 210, 313, 28);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("CIRCUNSTÂNCIAS DO ACOLHIMENTO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 100, 441, 32);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Contato:\n");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 175, 54, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Motivo(s) do acolhimento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 250, 190, 17);

        chEntregaVoluntaria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chEntregaVoluntaria.setText("Entrega voluntária");
        getContentPane().add(chEntregaVoluntaria);
        chEntregaVoluntaria.setBounds(10, 280, 138, 18);

        chViolenciaFisica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chViolenciaFisica.setText("Violência física");
        getContentPane().add(chViolenciaFisica);
        chViolenciaFisica.setBounds(10, 310, 115, 18);

        chExploracaoSexual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chExploracaoSexual.setText("Exploração sexual / rua / mendicâcia");
        getContentPane().add(chExploracaoSexual);
        chExploracaoSexual.setBounds(10, 340, 252, 18);

        chAmeacaMorte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chAmeacaMorte.setText("Ameaça de morte dos pais / por doença");
        getContentPane().add(chAmeacaMorte);
        chAmeacaMorte.setBounds(10, 370, 274, 18);

        chPaisResponsaveis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chPaisResponsaveis.setText("Pais / responsáveis alcoólatras");
        getContentPane().add(chPaisResponsaveis);
        chPaisResponsaveis.setBounds(10, 400, 218, 20);

        chOrfandade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chOrfandade.setText("Orfandade");
        getContentPane().add(chOrfandade);
        chOrfandade.setBounds(450, 260, 90, 18);

        chViolenciaPsicologica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chViolenciaPsicologica.setText("Violência psicologica");
        getContentPane().add(chViolenciaPsicologica);
        chViolenciaPsicologica.setBounds(450, 290, 153, 18);

        chTrabalhoInfantil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chTrabalhoInfantil.setText("Trabalho infantil");
        getContentPane().add(chTrabalhoInfantil);
        chTrabalhoInfantil.setBounds(450, 320, 124, 18);

        chAusenciaDosPaisPrisao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chAusenciaDosPaisPrisao.setText("Ausência dos pais / responsáveis por prisão ou internação");
        getContentPane().add(chAusenciaDosPaisPrisao);
        chAusenciaDosPaisPrisao.setBounds(10, 490, 392, 18);

        chAbandono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chAbandono.setText("Abandono");
        getContentPane().add(chAbandono);
        chAbandono.setBounds(450, 380, 87, 18);

        chAbusoSexual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chAbusoSexual.setText("Abuso sexual");
        getContentPane().add(chAbusoSexual);
        chAbusoSexual.setBounds(450, 410, 106, 18);

        chAusenciaResponsaveis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chAusenciaResponsaveis.setText("Ausência dos pais / responsáveis");
        getContentPane().add(chAusenciaResponsaveis);
        chAusenciaResponsaveis.setBounds(450, 440, 233, 18);

        chPaisDeficiencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chPaisDeficiencia.setText("Pais / Responsáveis com algum tipo de deficiência");
        getContentPane().add(chPaisDeficiencia);
        chPaisDeficiencia.setBounds(450, 470, 340, 18);

        chConflitoFamiliar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chConflitoFamiliar.setText("Conflito familiar");
        getContentPane().add(chConflitoFamiliar);
        chConflitoFamiliar.setBounds(450, 500, 119, 18);

        chPaisTranstornoMental.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chPaisTranstornoMental.setText("Pais / Responsáveis com transtorno mental / sofrimento psíquico");
        getContentPane().add(chPaisTranstornoMental);
        chPaisTranstornoMental.setBounds(10, 460, 429, 18);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Outro, Qual?:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 520, 86, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Considerando os motivos acima assinalados, informe quem é/são o(s)  ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(810, 160, 450, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("suposto(s) autor(es) da violência/violação de direitos ou responsável(is) que  ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(810, 180, 500, 17);

        chMae.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chMae.setText("Mãe ");
        getContentPane().add(chMae);
        chMae.setBounds(810, 230, 53, 18);

        chPai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chPai.setText("Pai");
        getContentPane().add(chPai);
        chPai.setBounds(810, 250, 42, 18);

        chMadrastra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chMadrastra.setText("Madrasta");
        getContentPane().add(chMadrastra);
        chMadrastra.setBounds(810, 270, 81, 18);

        chPadrasto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chPadrasto.setText("Padrasto");
        getContentPane().add(chPadrasto);
        chPadrasto.setBounds(810, 290, 80, 18);

        chIrmao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chIrmao.setText("Irmão(a)");
        getContentPane().add(chIrmao);
        chIrmao.setBounds(910, 230, 75, 18);

        chTio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chTio.setText("Tio(a)");
        getContentPane().add(chTio);
        chTio.setBounds(910, 250, 60, 18);

        chPrimo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chPrimo.setText("Primo(a)");
        getContentPane().add(chPrimo);
        chPrimo.setBounds(910, 270, 76, 18);

        chAvo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chAvo.setText("Avó(ô)");
        getContentPane().add(chAvo);
        chAvo.setBounds(910, 290, 64, 18);

        chNaoSeAplica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chNaoSeAplica.setText("Não se Aplica");
        getContentPane().add(chNaoSeAplica);
        chNaoSeAplica.setBounds(1000, 230, 108, 18);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Outro? Especifique:\n");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(810, 320, 125, 20);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Com quem a criança/adolescente residia antes da aplicação da medida ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(790, 390, 460, 19);

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(930, 570, 90, 40);

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/disquete.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(830, 570, 90, 40);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(414, 496, 20, 0);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("está(ão) impossibilitado(s) de prestar os cuidados:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(810, 200, 320, 17);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("protetiva de acolhimento? Informe nome completo e parentesco:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(790, 410, 490, 19);

        btnProx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Seta.png"))); // NOI18N
        btnProx.setText("Próxma etapa");
        btnProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxActionPerformed(evt);
            }
        });
        getContentPane().add(btnProx);
        btnProx.setBounds(1130, 570, 150, 40);

        btnAnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SetaE.png"))); // NOI18N
        btnAnt.setText("Página anterior");
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnt);
        btnAnt.setBounds(670, 570, 150, 40);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(1030, 570, 90, 40);

        txtnomecompletoeparen.setColumns(20);
        txtnomecompletoeparen.setLineWrap(true);
        txtnomecompletoeparen.setRows(5);
        txtnomecompletoeparen.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtnomecompletoeparen);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(800, 430, 450, 120);

        txtEspecifique.setColumns(20);
        txtEspecifique.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEspecifique.setLineWrap(true);
        txtEspecifique.setRows(5);
        txtEspecifique.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtEspecifique);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(940, 320, 310, 60);

        try {
            txtContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtContato.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtContato);
        txtContato.setBounds(660, 170, 120, 29);

        chPaisResponsaveisDrogas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chPaisResponsaveisDrogas.setText("Pais / responsavéis usuários abusivos de drogas");
        getContentPane().add(chPaisResponsaveisDrogas);
        chPaisResponsaveisDrogas.setBounds(450, 350, 340, 18);

        chNegligencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chNegligencia.setText("Negligência");
        getContentPane().add(chNegligencia);
        chNegligencia.setBounds(10, 430, 100, 18);
        getContentPane().add(txtOutQual);
        txtOutQual.setBounds(100, 520, 350, 28);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1511-horz.jpg"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1680, 860);

        setSize(new java.awt.Dimension(1301, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNomerespon.setText("");
        txtFuncResp.setText("");
        txtContato.setText("");
        txtOutQual.setText("");
        txtEspecifique.setText("");
        chEntregaVoluntaria.setSelected(false);
        chViolenciaFisica.setSelected(false);
        chExploracaoSexual.setSelected(false);
        chAmeacaMorte.setSelected(false);
        chPaisResponsaveis.setSelected(false);
        chOrfandade.setSelected(false);
        chViolenciaPsicologica.setSelected(false);
        chTrabalhoInfantil.setSelected(false);
        chAusenciaDosPaisPrisao.setSelected(false);
        chPaisResponsaveisDrogas.setSelected(false);
        chAbandono.setSelected(false);
        chAbusoSexual.setSelected(false);
        chAusenciaResponsaveis.setSelected(false);
        chPaisDeficiencia.setSelected(false);
        chConflitoFamiliar.setSelected(false);
        chNegligencia.setSelected(false);
        chPaisTranstornoMental.setSelected(false);
        chMae.setSelected(false);
        chPai.setSelected(false);
        chMadrastra.setSelected(false);
        chPadrasto.setSelected(false);
        chIrmao.setSelected(false);
        chTio.setSelected(false);
        chPrimo.setSelected(false);
        chAvo.setSelected(false);
        chNaoSeAplica.setSelected(false);

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        //Gravar
        //inserir//
        try {
            /*Connection - classe usada para estabelecer uma conexão com o banco. Neste momento devemos informar
            o endereço do servidor(IP) o nome do Banco e o usuário e nenha de acesso   */
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;// String para receber a Scrip(O comando SQL que será usado-Insert/Update/DLETE)
            sql = "INSERT INTO circ_do_acolhimen(Nome_Respon,Funcao_Respon,Contato,Entrega_volun,Violencia_Fisica,Explo_Rua_Mendi,Ameaca_doenca,"
                    + "Pais_Respo,Negligencia,Pais_Respon_Sofri,Ausencia_Respon,Orfandade,Violencia_Psi,Trabalho_Infantil,Respon_Usuario,Abandono,"
                    + "Abuso_sexual,Ausencia_dos_Pais,Pais_Respo_Defi,Conflito_Familiar,Outro_Qual,Mae,Pai,Madrasta,Padrasto,Irmao_a,Tio_a,Primo_a,"
                    + "Avo_o,Nao_se_Aplica,Especifique,Observacao)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement ps;
            ps = con.prepareStatement(sql);
            ps.setString(1, txtNomerespon.getText());
            ps.setString(2, txtFuncResp.getText());
            ps.setString(3, txtContato.getText());

            if (chEntregaVoluntaria.isSelected()) {
                ps.setBoolean(4, true);
            } else {
                ps.setBoolean(4, false);
            }
            if (chViolenciaFisica.isSelected()) {
                ps.setBoolean(5, true);
            } else {
                ps.setBoolean(5, false);
            }
            if (chExploracaoSexual.isSelected()) {
                ps.setBoolean(6, true);
            } else {
                ps.setBoolean(6, false);
            }
            if (chAmeacaMorte.isSelected()) {
                ps.setBoolean(7, true);
            } else {
                ps.setBoolean(7, false);
            }
            if (chPaisResponsaveis.isSelected()) {
                ps.setBoolean(8, true);
            } else {
                ps.setBoolean(8, false);
            }
            if (chNegligencia.isSelected()) {
                ps.setBoolean(9, true);
            } else {
                ps.setBoolean(9, false);
            }
            if (chPaisTranstornoMental.isSelected()) {
                ps.setBoolean(10, true);
            } else {
                ps.setBoolean(10, false);
            }
            if (chAusenciaDosPaisPrisao.isSelected()) {
                ps.setBoolean(11, true);
            } else {
                ps.setBoolean(11, false);
            }
            if (chOrfandade.isSelected()) {
                ps.setBoolean(12, true);
            } else {
                ps.setBoolean(12, false);
            }
            if (chViolenciaPsicologica.isSelected()) {
                ps.setBoolean(13, true);
            } else {
                ps.setBoolean(13, false);
            }
            if (chTrabalhoInfantil.isSelected()) {
                ps.setBoolean(14, true);
            } else {
                ps.setBoolean(14, false);
            }
            if (chPaisResponsaveisDrogas.isSelected()) {
                ps.setBoolean(15, true);
            } else {
                ps.setBoolean(15, false);
            }
            if (chAbandono.isSelected()) {
                ps.setBoolean(16, true);
            } else {
                ps.setBoolean(16, false);
            }
            if (chAbusoSexual.isSelected()) {
                ps.setBoolean(17, true);
            } else {
                ps.setBoolean(17, false);
            }
            if (chAusenciaResponsaveis.isSelected()) {
                ps.setBoolean(18, true);
            } else {
                ps.setBoolean(18, false);
            }
            if (chPaisDeficiencia.isSelected()) {
                ps.setBoolean(19, true);
            } else {
                ps.setBoolean(19, false);
            }
            if (chConflitoFamiliar.isSelected()) {
                ps.setBoolean(20, true);
            } else {
                ps.setBoolean(20, false);
            }

            ps.setString(21, txtOutQual.getText());

            if (chMae.isSelected()) {
                ps.setBoolean(22, true);
            } else {
                ps.setBoolean(22, false);
            }
            if (chPai.isSelected()) {
                ps.setBoolean(23, true);
            } else {
                ps.setBoolean(23, false);
            }
            if (chMadrastra.isSelected()) {
                ps.setBoolean(24, true);
            } else {
                ps.setBoolean(24, false);
            }
            if (chPadrasto.isSelected()) {
                ps.setBoolean(25, true);
            } else {
                ps.setBoolean(25, false);
            }
            if (chIrmao.isSelected()) {
                ps.setBoolean(26, true);
            } else {
                ps.setBoolean(26, false);
            }
            if (chTio.isSelected()) {
                ps.setBoolean(27, true);
            } else {
                ps.setBoolean(27, false);
            }
            if (chPrimo.isSelected()) {
                ps.setBoolean(28, true);
            } else {
                ps.setBoolean(28, false);
            }
            if (chAvo.isSelected()) {
                ps.setBoolean(29, true);
            } else {
                ps.setBoolean(29, false);
            }
            if (chNaoSeAplica.isSelected()) {
                ps.setBoolean(30, true);
            } else {
                ps.setBoolean(30, false);
            }

            ps.setString(31, txtEspecifique.getText());
            ps.setString(32, txtnomecompletoeparen.getText());

            /* A Script é executada e se retornar algo significa que ocorreu com sucesso*/
            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Falha no Cadastro");
            }
        } catch (SQLException ex)//Se ocorrer algum erro uma mensagem é exibida.
        {
            JOptionPane.showMessageDialog(null, "SQLException: ");
            JOptionPane.showMessageDialog(null, "SQLException: " + ex.getMessage() + "\nSQLState: " + ex.getSQLState()
                    + "\nVendorError: " + ex.getErrorCode());
        }

    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        InfCA pnelso = new InfCA();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnAntActionPerformed

    private void btnProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxActionPerformed
        ComposicaoFamiliar pnelso = new ComposicaoFamiliar();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnProxActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu pnelso = new Menu();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_3CDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_3CDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_3CDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_3CDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_3CDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnProx;
    private javax.swing.JCheckBox chAbandono;
    private javax.swing.JCheckBox chAbusoSexual;
    private javax.swing.JCheckBox chAmeacaMorte;
    private javax.swing.JCheckBox chAusenciaDosPaisPrisao;
    private javax.swing.JCheckBox chAusenciaResponsaveis;
    private javax.swing.JCheckBox chAvo;
    private javax.swing.JCheckBox chConflitoFamiliar;
    private javax.swing.JCheckBox chEntregaVoluntaria;
    private javax.swing.JCheckBox chExploracaoSexual;
    private javax.swing.JCheckBox chIrmao;
    private javax.swing.JCheckBox chMadrastra;
    private javax.swing.JCheckBox chMae;
    private javax.swing.JCheckBox chNaoSeAplica;
    private javax.swing.JCheckBox chNegligencia;
    private javax.swing.JCheckBox chOrfandade;
    private javax.swing.JCheckBox chPadrasto;
    private javax.swing.JCheckBox chPai;
    private javax.swing.JCheckBox chPaisDeficiencia;
    private javax.swing.JCheckBox chPaisResponsaveis;
    private javax.swing.JCheckBox chPaisResponsaveisDrogas;
    private javax.swing.JCheckBox chPaisTranstornoMental;
    private javax.swing.JCheckBox chPrimo;
    private javax.swing.JCheckBox chTio;
    private javax.swing.JCheckBox chTrabalhoInfantil;
    private javax.swing.JCheckBox chViolenciaFisica;
    private javax.swing.JCheckBox chViolenciaPsicologica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JFormattedTextField txtContato;
    private javax.swing.JTextArea txtEspecifique;
    private javax.swing.JTextField txtFuncResp;
    private javax.swing.JTextField txtNomerespon;
    private javax.swing.JTextField txtOutQual;
    private javax.swing.JTextArea txtnomecompletoeparen;
    // End of variables declaration//GEN-END:variables
}
