/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacasulono;

import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Trentim
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCriancaAdoles = new javax.swing.JMenuItem();
        jFuncionario = new javax.swing.JMenuItem();
        jPesquisa = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSair = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiniLogo.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 250, 300, 147);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fundo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 920, 635);

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Cadastrar");

        jCriancaAdoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jCriancaAdoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Adolescente.png"))); // NOI18N
        jCriancaAdoles.setText("Criança/Adolescente");
        jCriancaAdoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCriancaAdolesActionPerformed(evt);
            }
        });
        jMenu1.add(jCriancaAdoles);

        jFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Funcionario.png"))); // NOI18N
        jFuncionario.setText("Funcionário");
        jFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(jFuncionario);

        jMenuBar1.add(jMenu1);

        jPesquisa.setText("Pesquisar");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa2.png"))); // NOI18N
        jMenuItem3.setText("Criança/Adolescente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPesquisa.add(jMenuItem3);

        jMenuBar1.add(jPesquisa);

        jSair.setText("Sair");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jSair.add(jMenuItem4);

        jMenuBar1.add(jSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(919, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair do sistema?", "Alerta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (sair == JOptionPane.YES_OPTION) {
            TelaLogin pnelso = new TelaLogin();
            pnelso.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFuncionarioActionPerformed
        CadastroFuncionario pnelso = new CadastroFuncionario();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_jFuncionarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Pesquisa pnelso = new Pesquisa();
        pnelso.setVisible(true);

        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jCriancaAdolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCriancaAdolesActionPerformed
        InformacoesGerais curso = new InformacoesGerais();
        curso.setVisible(true);

        dispose();
    }//GEN-LAST:event_jCriancaAdolesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCriancaAdoles;
    private javax.swing.JMenuItem jFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jPesquisa;
    private javax.swing.JMenu jSair;
    // End of variables declaration//GEN-END:variables
}
