/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacasulono;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VPLima-Inf181
 */
public class Pesquisa extends javax.swing.JFrame {

    /**
     * Creates new form Pesquisa
     */
    public Pesquisa() {
        initComponents();
        getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDigiteNome = new javax.swing.JLabel();
        txtNomeCriAd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        btnRetornar = new javax.swing.JButton();
        btnRegistrarAdocao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Pesquisa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(650, 30, 105, 32);

        lblDigiteNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDigiteNome.setText("Digite o nome do(a) criança/adolescente:");
        getContentPane().add(lblDigiteNome);
        lblDigiteNome.setBounds(330, 85, 325, 22);

        txtNomeCriAd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtNomeCriAd);
        txtNomeCriAd.setBounds(660, 80, 349, 36);

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Criança/Adolescente", "Sem registro", "Nome completo", "Como prefere ser chamado(a)", "Sexo", "Cor/Raça", "Nacionalidade", "Naturalidade", "Data de Nascimento", "Idade", "Idade Presu", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 140, 1280, 460);

        btnRetornar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        btnRetornar.setText("Menu");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetornar);
        btnRetornar.setBounds(1190, 604, 82, 40);

        btnRegistrarAdocao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrarAdocao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borracha.png"))); // NOI18N
        btnRegistrarAdocao.setText("Registrar Adoção");
        btnRegistrarAdocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAdocaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarAdocao);
        btnRegistrarAdocao.setBounds(1010, 605, 160, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MiniLogo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 320, 140);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lupa_1.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(1010, 80, 40, 34);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1511-horz.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1440, 660);

        setSize(new java.awt.Dimension(1278, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAdocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAdocaoActionPerformed

        int linha = tblDados.getSelectedRow();

        String valor = String.valueOf(tblDados.getValueAt(linha, 0).toString());
        //JOptionPane.showMessageDialog(null, "Criança" + valor);
        try {

            Connection con;
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql;// String para receber a Scrip(O comando SQL que será usado-Insert/Update/DLETE)
            sql = "update info_crianca_adolescente set situacao = 'adotado' where ID_Crianca_Adoles = ?";
            PreparedStatement ps;
            ps = con.prepareStatement(sql);
            ps.setString(1, valor);
            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Adoção feita com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Falha na alteração!!");
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarAdocaoActionPerformed

    private void tblDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDadosMouseClicked

    }//GEN-LAST:event_tblDadosMouseClicked

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed

        Menu curso = new Menu();
        curso.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/sistemacasulo", "root", "");
            String sql = null;
            sql = "SELECT * FROM info_crianca_adolescente WHERE Nome_Comp LIKE ?";
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, "%" + txtNomeCriAd.getText() + "%");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel m = (DefaultTableModel) tblDados.getModel();
            //limpar o jTable
            while (tblDados.getRowCount() > 0) {
                m.removeRow(0); //apaga a primeira linha
            }
            //transferir o conteúdo do rs para o jTable1
            while (rs.next()) {//enquanto existirem registros
                Object linha[] = new Object[13]; //vetor com 13 elementos
                linha[0] = rs.getInt("ID_Crianca_Adoles");
                linha[1] = rs.getBoolean("Sem_Registro");//pegando cada um dos campos
                linha[2] = rs.getString("Nome_Comp");
                linha[3] = rs.getString("Como_Chamar");
                linha[4] = rs.getString("Sexo");
                linha[5] = rs.getString("Cor_raca");
                linha[6] = rs.getString("Nacionalidade");
                linha[7] = rs.getString("Naturalidade");
                linha[8] = rs.getString("Data_nasc");
                linha[9] = rs.getString("Idade");
                linha[10] = rs.getBoolean("Idade_presu");
                linha[11] = rs.getString("situacao");
                m.addRow(linha);//adicionado o vetor ao jTable1
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQLException" + ex.getMessage() + "\nSQLState" + ex.getSQLState() + "\nVendorError");

        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRegistrarAdocao;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDigiteNome;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtNomeCriAd;
    // End of variables declaration//GEN-END:variables
}
